### ISSUE TITLE
CoreLocation requestLocation hangs on iOS Simulator

### ISSUE THREAD

**Issue by tpoche** [mxcl/PromiseKit#1029]
The `CLLocationManager.requestLocation` promise hangs when running on a simulator without an emulated device location (ie. Debug > Location > None from the simulator window menu).  You can duplicate this error with the following unit test (make sure to run on simulator with setting as defined above):

```
    func testPromiseKitLocationUnknown() {
        let expect = expectation(description: "PromiseKit Location Unknown")
        CLLocationManager.requestLocation(authorizationType: .whenInUse).done { locations in
            XCTAssertTrue(locations.isEmpty)
            expect.fulfill()
        }.catch { _ in XCTFail("requestLocation should not throw any errors!") }

        waitForExpectations(timeout: 1)
    }
```

The problem appears to be related to Issue #241 in that the simulator is throwing the kCLErrorLocationUnknown which PromiseKit explicitly ignores.  I understand the reasoning behind ignoring this error in certain scenarios as Apple suggests, but should it be ignored all the time?  Would it be worth adding logic to _not_ ignore the error when running on a simulator (ie. `#if (arch(i386) || arch(x86_64)`)?

PromiseKit v6.8.3
Installed through Cocoapods

**Comment by mxcl** [comment]
We could put an #if debug in and log a message.

**Comment by r3econ** [comment]
This happens to me on device as well. I had to rewrite a part of my app to use native frameworks again. Again, using 3rd party libraries bites back...

**Comment by mxcl** [comment]
I've been using PromiseKit for 6 years, and have never seen this on a device, only in the simulator.

We are doing what Apple recommend here, the only thing we could do to help for simulator users that have no location specified for the simulator is to log something.

But if you have any further info about what you saw on the device, please specify.

I'm sorry PromiseKit let you down, I'm sorry the literally thousands of hours I dedicated to this library left a small hole in it that made you snotty about all third party libraries. In future I sincerely recommend you use none of them, since we'd rather not have your snotty retorts on our issue trackers.

Thanks.

**Comment by mxcl** [comment]
With v7 we log a message for this case.

**Comment by tpoche** [comment]
Thanks @mxcl for keeping this on your radar for so long!  I'll go ahead and close out this ticket now
