### ISSUE TITLE
Cannot invoke when

### ISSUE THREAD

**Issue by James-Sangalli** [mxcl/PromiseKit#1055]
I am returning a void promise in this code: 

`private func autoDetectTransactedTokensImpl(wallet: Address, erc20: Bool) -> Promise<Void> {
        return Promise<Void> { seal in
            GetContractInteractions().getContractList(address: wallet.eip55String, server: session.server, erc20: erc20) { [weak self] contracts in
                defer {
                    seal.fulfill(())
                }
...
    }`

And in another file, I use the when function to wait for its completion:

`override func main() {
            let fetchErc20Tokens = coordinator?.autoDetectTransactedTokensImpl(wallet: wallet, erc20: true)
            let fetchNonErc20Tokens = coordinator?.autoDetectTransactedTokensImpl(wallet: wallet, erc20: false)
            when(fulfilled: fetchErc20Tokens, fetchNonErc20Tokens).isFulfilled {
                guard let strongSelf = self else { return }
                strongSelf.willChangeValue(forKey: "isExecuting")
                strongSelf.willChangeValue(forKey: "isFinished")
                strongSelf.coordinator?.isAutoDetectingTransactedTokens = false
                strongSelf.didChangeValue(forKey: "isExecuting")
                strongSelf.didChangeValue(forKey: "isFinished")
            }
        }`

I get back the error: 

> Error:(532, 13) cannot invoke 'when' with an argument list of type '(fulfilled: Promise<Void>?, Promise<Void>?)'

I thought that this might be caused by having optional types, but making them solid gives the same error. 

Thanks

**Comment by GarthSnyder** [comment]
Yes, you need real promises here, not optionals.

I'm not sure this is the root of your problem, but you probably intend `done` rather than `isFulfilled`. `isFulfilled` just returns a bool indicating whether the promise has already been fulfilled; it doesn't take a closure argument.

There are versions of `when` that might return either a `Promise<Void>` or a `Promise<(Void, Void)>` when the arguments are two void promises. Seeing a `done` for which the closure doesn't expect an argument allows the compiler to disambiguate.

Try fixing that and see if it resolves the problem.

**Comment by James-Sangalli** [comment]
@GarthSnyder it works when I change it to done and make the variables strong. Thank you for your help.
