### ISSUE TITLE
Getting warning Module 'PromiseKit' was not compiled with library evolution support

### ISSUE THREAD

**Issue by yo2bh** [mxcl/PromiseKit#1137]
I am getting below warning while compiling the application.

_"Module 'PromiseKit' was not compiled with library evolution support; using it means binary compatibility for 'MyFramework' can't be guaranteed"_

Following are the Promisekit details:
_Version_ - 6.8.4
_Installed_ - Carthage.

How to resolve this warning so that this will not reflect in warning?

**Comment by martinpucik** [comment]
@yo2bh did you try to rebuild your Carthage dependencies with the latest Xcode?

**Comment by yo2bh** [comment]
@martinpucik - I am using latest version of Xcode 11.3. Still facing the same issue.

**Comment by bielikb** [comment]
@yo2bh You're seeing this warning since you're building framework with module stability turned on == you're setting `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`  in your build settings/xcconfig.

This flag shouldn't be pushed to all `PromiseKit` users, though, since it's not required for schemes that do build apps.

To resolve this issue, I'd suggest trying to build/update the `PromiseKit` dependency with `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` flag. If you'll hit any issues with turning the module stability on in the `PromiseKit`, open another issue that will reflect that specific issue.

_Note:_
I've written couple words about the xcframeworks & module stabillity here https://github.com/bielikb/xcframeworks, including [Testing & Troubleshooting](https://github.com/bielikb/xcframeworks#testing--troubleshooting) section

**Comment by RomanPodymov** [comment]
Hello @yo2bh 
Can you reproduce this issue in Xcode 12?

**Comment by mxcl** [comment]
Presumably no longer an issue.
