### ISSUE TITLE
Dealing with Promise/Guarantee<Void> and () -> Void completions

### ISSUE THREAD

**Issue by Drekka-IAG** [mxcl/PromiseKit#1158]
This is more a question than bug.

I find myself quite often interfacing between non-PromiseKit code that uses `() -> Void` closures. The problem I keep encountering is that I need to pass a seal as the completion. So for example I might be doing something like this (simplified):

    func someFunc(completion: () -> Void) { /* ... */ }
    
    Guarantee<Void> { seal in
        someFunc { seal(()) }
    }

When really I'd like to do something like this:

    Guarantee<Void>(resolver: someFunc)

The problem comes from Swift seeing the closures for a `Void` promise or guarantee as `(Void) -> Void` rather than `() -> Void`. 

Is there any 'nifty' way around this is? I've tried a couple of extensions to `Promise` and `Guarantee` when `T == Void` to help with this but so far they've not been as helpful as I'd like and have created some confusion for Swift.

**Comment by GarthSnyder** [comment]
Swift has historically been a bit squirrely about Void. PromiseKit supplies Void-specific overrides for a variety of functions because of the exact problems you describe above. In fact, the (alpha) V7 already includes a Void-specific version of Guarantee(resolver:), but this initializer is disabled for Swift versions below 5.1 because (as you discovered) it confuses earlier versions of Swift.

Your code should work as you expect in the current Xcode beta (version 12). If you're using PromiseKit 6, you'll need to include your own override for Void; however, Swift should no longer give you ambiguity complaints.

The short-term fix is to just work around the problem in whatever inelegant way you need to. Just plan on fixing the problem for real when you're able to migrate to a later version of Swift.

**Comment by Drekka-IAG** [comment]
Thanks for that. Unfortunately I'm using PK6 on a client's project with Xcode 11 but that's life. Thanks for the advice.
