### ISSUE TITLE
Question about references 

### ISSUE THREAD

**Issue by emartynov** [mxcl/PromiseKit#140]
Hi,

We are mixing passing weak and strong references into callbacks but it is because we don't understand completely what happens with them after promise is finished. What is common rule of passing ```self``` reference in promise callback blocks? 

Thank you in advance!

**Comment by mxcl** [comment]
If the promise is eventually resolved, strong references are fine.

The Promise object itself is careful to release everything after it is resolved, so all your callbacks will be released.

Even if you hold a strong reference to the Promise itself, you can pass strong references into the callbacks. This is because the callback blocks/closures are released once the Promise is resolved.

So, as long as the Promise resolves, you're good. All Promises from PMK itself will resolve, so it's just up to you with your own promises.
