### ISSUE TITLE
Canceling a promise

### ISSUE THREAD

**Issue by dbachrach** [mxcl/PromiseKit#18]
Consider an asynchronous HTTP GET method request that returns a promise:

```
- (Promise*)GET:(NSString*)path;
```

Users of this API may want to cancel the underlying asynchronous work, the HTTP request. Currently PromiseKit does not allow cancelable promises.

I've been looking into javascript promises and cancelation. There is some discussion in the A+ spec https://github.com/promises-aplus/cancellation-spec/issues

Any thoughts on cancelation?

**Comment by jkolb** [comment]
@kriskowal Thank you, I had found that link somewhere but it was tricky to stumble onto when searching on the subject of promise cancellation. The last paragraph in it gave me inspiration.

In my promises library I've implemented cancellation by tying it to the lifetime of the Promise. When a promise is deinitialized the work it is doing can be cancelled early if not already finished. Only if all promises depending on another promise are deinitialized will it really cancel, otherwise it must stay alive and finish its work for the ones that are keeping it alive. Just because one section of the code cancelled doesn't mean other places in the code should be interrupted. The application programmer can then structure the promises to support early cancellation by making sure when needed they can be deinitialized at appropriate times.

To help support this, when you create a new promise you are provided with `fulfill`, `reject`, and `isCancelled` callbacks. Both `fulfill` and `reject` have weak references to the original promise so that if you call them and the promise has been deinitialized they safely have no effect. The `isCancelled` callback allows your long running background process to periodically call it to see if the owning promise has been deinitialized and exit early if it has. All promises in a chain have a reference to their parent promise and any promises returned within their callbacks, that way the lifetime of a promise is well defined. As long as the last promise returned from `then` is alive, then the entire chain is alive.

Any thoughts on if this is a viable strategy for implementing cancellation for PromiseKit?

**Comment by mxcl** [comment]
2.0 supports the idea of cancellation. Promises themselves cannot be cancelled, but the task they represent can (eg. `[NSURLConnection cancel]`). The promise then must ensure PromiseKit knows the specific NSError object that is generated is a cancellation error.

Cancellation errors skip to the next catch, but the catch handler is not executed unless it is called with `catch(policy: .AllErrors)`.

This seemed the correct way to handle a cancellation. Not all promises are cancelable, promises that cancel do not resolve their chain. The catch handler usually is not interested in cancellation since either the user or the developer decided to end the chain explicitly, it is not strictly an error. Eg. with a typical flow with something that is cancellable:

```
UIApplication.sharedApplication().networkActivityIndicatorVisible = true
let cancellableThing = CancellableThing()
cancellableThing.go().then {
    //…
}.then {
    //…
}.finally {
    UIApplication.sharedApplication().networkActivityIndicatorVisible = false
}.catch { err in
    UIAlertView.show(err)
}

cancellableThing.cancel()
```

Here the finally will undo the UI changes but an error alert view will not be shown to the user. Here the developer decided to cancel the chain, presumably because they no longer care about the result. In such a situation neither an error should occur nor should the chain itself have to identify and handle that situation. Let's compare with what is necessary for an alert view in PromiseKit 1.x:

```
UIAlertView(…).promise().then { dismissedButtonIndex in
    if dismissedButtonIndex != alert.cancelButtonIndex {
        foo().then {
            // rightward drift
        }
    }
}
```

Rightward drift. Yuck.

Let me know if I should leave this open.

**Comment by dbachrach** [comment]
This all seems to make a lot of sense. I like the default policy of not raising cancelations to catch blocks, but do allow it via explicit indication. In the `ensure()` example we discussed previously, ensure could just be a generic extension to PromiseKit that would raise the cancelation NSError. I think that pattern needs to be vetted before inclusion in the library, though. I think this issue can be closed. Thanks Max.
