### ISSUE TITLE
'catch' is now a reserved keyword in Swift 2.0, making it invalid for use as a method name

### ISSUE THREAD

**Issue by apendley** [mxcl/PromiseKit#199]
Propose renaming to "failed" or something similar.

**Comment by mxcl** [comment]
Can I confirm you tested this?

**Comment by apendley** [comment]
I have not yet tested this yet, however the new reference is available at https://itunes.apple.com/us/book/swift-programming-language/id1002622538?mt=11.

In this reference, "catch" has been added as a reserved keyword. 

I will be downloading the Xcode 7 beta later today, at which time I will test this to verify, and will update here after I've done so.

**Comment by mxcl** [comment]
Yeah, I'm downloading too. This would suck if true, but such is life.

**Comment by schemers** [comment]
so is defer

**Comment by mxcl** [comment]
Oh FFS.

**Comment by mxcl** [comment]
Options to replace `catch`:

* `p.then{ /*…*/ }.error { error in }`
* `p.then{ /*…*/ }.onfail { error in }`
* `p.then{ /*…*/ }.fail { error in }`
* `p.then{ /*…*/ }.failed { error in }`
* `p.then{ /*…*/ }.clasp { error in }`
* `p.then{ /*…*/ }.onerror { error in }`
* `p.then{ /*…*/ }.onerror { error in }`

Options for `defer`:

* let (promise, fulfill, reject) = Promise<Int>.deferred()
* let (promise, fulfill, reject) = Promise<Int>.tuple()
* let (promise, fulfill, reject) = Promise<Int>.breakOut()

**Comment by apendley** [comment]
FWIW:
For `catch` replacement, I like `fail` or `failed`.

For `defer` replacement I like `deferred()`. My rationale for this is that using the alternate form:
`let deferred = Promise<Int>.deferred()` 
seems more natural than the other alternatives, as would accessing it's members:
`deferred.promise`, `deferred.fulfil`, `deferred.reject`.

**Comment by mxcl** [comment]
fail is not my favorite, it doesn’t read as well as catch. I'm still thinking of more ideas, the above list is not the final list.

**Comment by ZerdaH** [comment]
Coming from JS promises, `deferred` was commonly used and is a natural replacement.

**Comment by mxcl** [comment]
Preliminary swift 2.0 branch here: https://github.com/mxcl/PromiseKit/tree/swift-2.0

It compiles, some UI tests are disabled. The name `snatch` is not final.

**Comment by pjechris** [comment]
What about `rescue`? This is used in Ruby and I guess some other languages.
IMO It's give a good insight of what it is doing, juste like `catch`

**Comment by mxcl** [comment]
The current branch is now `rescue`. Though I'm not 100% sure yet since PromiseKit doesn't rescue errors, since the app survives if you don't.

**Comment by mxcl** [comment]
I pushed some additional revisions so you can throw in most swift methods.

**Comment by mowens** [comment]
Not really sure that `rescue` is a great name for the new catch which @mxcl  has already mentioned doesn't actually rescue from errors. Additionally there is already a `recover` feature which *does* rescue from errors and recovery is a [synonym](http://www.thesaurus.com/browse/rescue) for rescue

**Comment by mxcl** [comment]
Also, Swift “exceptions” don’t crash the app either; instead you *must* handle them, you cannot write code that does not.

Ideally we’d keep the same pattern for Promise, but I fail to see how that can be done since we are not writing the compiler.

**Comment by deville** [comment]
Has the decision been made yet? If not, what about
`p.then{ /*…*/ }.ifFailed { error in }`
`p.then{ /*…*/ }.whenFailed { error in }`
?

**Comment by mxcl** [comment]
No decision. I'm having sleepless nights about it.

**Comment by deville** [comment]
As for `defer`, I haven't used it much, so I might not completely understand its meaning, but `handle` (as in _door handle_) seems like a candidate to me. Or maybe some other, better name for _object_ which can be used to do stuff.

**Comment by mxcl** [comment]
For defer I made it `pendingPromise` which is more Cocoa like anyway.

**Comment by mxcl** [comment]
I think I’m happy with `report`. Here’s example usage: https://github.com/mxcl/PromiseKit/blob/swift-2.0-beta4/README.markdown

I changed `finally` to `ensure` since we had to change away from `catch` and `finally` is from the try, catch, finally pattern. And `finally` was a lie with the Swift version since 2.0 anyway since you couldn't do it after a `catch`.

I will probably add `ensure` and `report` as aliases for AnyPromise, but I don't wish to force the change when not necessary for all users.

Opinions welcome.

**Comment by mxcl** [comment]
Another options I was playing with was `done` where `done` provides two optionals thus replacing both the error handler and the “always” case, eg:

`foo.then {
    //…
}.done { value, error in
    if let error = error {
    }
}
```

But it seemed unnecessarily tedious for most usages I tried it with. Especially for the “always” case since I made it terminating (or it was hardly “done”).

**Comment by mythz** [comment]
Went to upgrade to Swift 2.0 and just found out `catch` was renamed to `report` which IMO is an unfamiliar and non-obvious replacement for `catch` that I don't think has any association with error handling. 

Looking at the existing naming used in a popular Promises like API like [jQuery ajax](http://api.jquery.com/jquery.ajax/), it uses `fail` for `catch` and `always` for `finally`:

```js
var jqxhr = $.ajax( "example.php" )
  .done(function() {
    alert( "success" );
  })
  .fail(function() {
    alert( "error" );
  })
  .always(function() {
    alert( "complete" );
  });
```

It also uses `done` for complete and `then` for chaining which supports an overload for both success and failed callbacks. This API is also what's defined in [ES6 Promises API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then):

```js
p.then(function(value) {
  console.log(value); // Success!
}, function(reason) {
  console.log(reason); // Error!
});
```

FWIW I think your earlier suggestions of:

  - fail
  - failed
  - error
  - onerror

Are all better replacements than report. I'd go with fail just because it's already a well known alias.

**Comment by mxcl** [comment]
My experience with users of this tool, hardly any of them are familiar with other promise implementations, or even the concept of promises.

Report reads well, you are being required to report on errors. fail does not read well, it is imperative, it reads as though you are instructing the promise chain to fail. `onFail` reads OK, but `on` as a prefix is not familiar to Cocoa.

`error` is used in Cocoa everywhere and means that an error is being passed in out, it is not an error handler.

So I minced many other alternatives, none are as good as `catch` and `finally` as they refer to an existing mechanism in Objective-C. Since I cannot use those, I ended up with `report`.

We have not merged 3.0.0 yet, but it is urgent that we do so. So if anyone has further input, it should happen quickly.

**Comment by mxcl** [comment]
I also wanted to communicate that the chain is terminated.

Other promise implementations do not terminate the chain at the error handler, but because of otherwise Swift finds ambiguity in all `catch` we had to change it to be terminating and add `recover` for the other usage.

`report` *sounds* **final**.

**Comment by mxcl** [comment]
I find my argument against `error` non-compelling though.

```swift
foo.then {
    //…
}.always {
    //…
}.error { error in
    //…
}
```

Looking at that, the only complaint I really have is that the token `error` repeats

**Comment by mythz** [comment]
> Looking at that, the only complaint I really have is that the token error repeats

Since it's something I do frequently I'd use an `e` or `ex` abbreviation myself. There's always `onerror` to differentiate from the `error

**Comment by adrianmacneil** [comment]
I'm fairly new to both Swift and this library, so take this with a grain of salt, but `.error` looks much nicer to me than `.report`. The problem with `.report` is that to me it reads as though it could be either positive or negative (am I reporting to the user that their download finished?). I agree with your points against `.fail` sounding imperative though.

Either way, look forward to an official release for Swift 2, thanks for all your hard work :+1:

**Comment by adrianmacneil** [comment]
Actually from reading the docs I can't figure out why both `catch` and `recover` exist in the current version. Why not just drop `catch`/`report`/`error` in favor of `.recover`? Is there a reason why one would want to use the former?

**Comment by mxcl** [comment]
Recover requires that you recover. You *must* return something that continues the chain. Catch terminates the chain. You can't continue with a then.

Which docs weren't clear may I ask? They should be improved.

**Comment by adrianmacneil** [comment]
Yeah, I eventually figured that out after reading the Scala promise docs and some other libraries. 

I was reading [this page](http://promisekit.org/recovering-from-errors/) which I found by Googling "promisekit recover vs catch". For someone who already knows why they would want to use recover it does a decent job of explaining the syntax, but it could probably use an introductory sentence explaining that recover is used to provide a default return value, and not for general error handling.

My search also returned your [blog post](http://promisekit.org/PromiseKit-2.0-Released/) which mentions that recover was added to "work around ambiguity in catch", which makes it sound like it's some sort of workaround and not a separate feature.

**Comment by mxcl** [comment]
The page you got from Google is part of the manual, you are expected to read what came before it, it is not designed for cherry-picking.

I understand that the layout of the page does not suggest where you are in the documentation.

But I only have so many hours I can spend on this project, the fact that there is documentation at all represents 100s of unpaid hours.

Pull requests welcome.
