### ISSUE TITLE
Carthage not including Categories

### ISSUE THREAD

**Issue by blakebyrnes** [mxcl/PromiseKit#240]
I can't seem to figure out how to make Carthage include the UIKit, Location, NSNotification, etc Categories.  Is it simply a matter of including the headers in the core project?

**Comment by mxcl** [comment]
The Carthage install does indeed *not* include categories.

The reason for this is Carthage has no “subspec” capability, so I can install *all* the categories or none of them. All is not reasonable because then any app would link to 20+ frameworks. Thus we link to none.

You must import the categories manually. Drag and drop from the carthage checkout folder.
