### ISSUE TITLE
Cannot find an initializer for type

### ISSUE THREAD

**Issue by sethsamuel** [mxcl/PromiseKit#253]
I'm working on moving a promisification of the MMX library from Obj-C to Swift. XCode is throwing an error at the Promise initialization:

`Cannot find an initializer for type 'Promise<T>' that accepts an argument list of type '((_, _) -> _)'`

Here's the entire extension:

```
import Foundation
import PromiseKit
import MMX

extension MMXChannel {
    class func findByTags (tags : [String]) -> Promise<(Int, [MMXChannel])> {
        return Promise { fulfill, reject in
            self.findByTags(tags,
                success: { (count : Int, channels: [MMXChannel]) -> Void in
                    fulfill(count, channels)
                },
                failure: { (error) -> Void in
                    reject(error)
                }
            )
        }
    }
}
```

**Comment by mxcl** [comment]
The Swift compiler is giving an incorrect error message due to neatest closures.

One of `fulfill` or `reject` is not correct in some syntatic manner or possibly the use of `self.findByTags` is incorrect syntactically.

Try the `self.findByTags` statement by itself without the `Promise` wrapping it.

You may also try: `fulfill((count, channels))` though not usually necessary, I've seen that satisfy the compiler once.

Possibly specifying `Promise { (fulfill, reject) -> Void in` will help, thought I doubt it.

Let me know if any of these work.

**Comment by sethsamuel** [comment]
Looks like it was a finicky casting issue. Thanks for the tips, still getting used to Swift and the compiler is, shall we say, less than helpful at times.
