### ISSUE TITLE
CocoaPods 3.0.0

### ISSUE THREAD

**Issue by zdenektopic** [mxcl/PromiseKit#291]
Hey,

I am unable to get 3.0.0 with cocoapods.
```
pod 'PromiseKit', '~> 3.0'
```

**Comment by nathanhosselton** [comment]
Yes, this will be fixed today.

**Comment by djtarazona** [comment]
:+1:

**Comment by explicitcall** [comment]
still not fixed :(

**Comment by mxcl** [comment]
For now you can trivially set your Podspec to use the branch, please don't badger Nathan, the poor guy has been thrown in the deep end on this stuff. He is working hard and we will push as soon as he can persuade CocoaPods to lint.

**Comment by zdenektopic** [comment]
You cant define branch in Podspec. You can do it in Podfile, but not in Podspec.

**Comment by mxcl** [comment]
Sorry, and yes, thanks—I meant Podfile.

**Comment by zdenektopic** [comment]
but it doesnt actually help if I need it in podspec :(

**Comment by svenmuennich** [comment]
Since we're desperately in need of a fix for this to use PromiseKit in one of our own pods, I looked into the linting problem. It looks like `v3.0.0` of [OMGHTTPURLRQ](https://github.com/mxcl/OMGHTTPURLRQ) is not ready for watchOS. I sent a PR (mxcl/OMGHTTPURLRQ#12) to OMGHTTPURLRQ which fixes a deprecation warning. As a result OMGHTTPURLRQ's podspec passes the linting for all platforms (incl. watchOS), which gives me hope that, if merged, PromiseKit will pass the linting too.

**Comment by svenmuennich** [comment]
I sent a PR [#294](https://github.com/mxcl/PromiseKit/pull/294) which makes the podspec lint again. For more details please check its description.

**Comment by nathanhosselton** [comment]
3.0.0 is now available via CocoaPods
