### ISSUE TITLE
Suppress deprecation warnings in UIActionSheet+PromiseKit

### ISSUE THREAD

**Issue by xezero** [mxcl/PromiseKit#306]
Can we suppress these warnings somehow? Or, since we can explicitly import the PromiseKit/UIKit pod separately anyways, could we maybe remove this extension by default from the umbrella pod?

```
'UIActionSheet' was deprecated in iOS 8.3: UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
```

**Comment by mxcl** [comment]
It is impossible to suppress deprecation warnings. I agree it sucks. I have not come up with a solution.

**Comment by mxcl** [comment]
We can't remove this category from the umbrella pod because CocoaPods offers no way to selectively remove files based on deployment target. And people may still need this category. Splitting it out would be a breaking change.

**Comment by xezero** [comment]
Ah, darn. Thanks anyways!

**Comment by mxcl** [comment]
I've removed deprecated stuff from PMK4 since it has been two years since the deprecation now. They are going to be still available in a subspec. Nothing else we've been able to do, removing them outright earlier would have been outrageous to people who needed them. CocoaPods doesn't let us turn on no warnings, and you can't turn off warnings in the source code in Swift (just objc).
