### ISSUE TITLE
Proposal: Don't force errors into .When(...) in all cases

### ISSUE THREAD

**Issue by radex** [mxcl/PromiseKit#341]
When using `when` to join a collection of promises and an error occurs, the error is wrapped in `PromiseKit.Error.When(index, actualError)`. This makes a lot of sense in some cases, because if you care about which promise in the collection failed, the enum case has a helpful index field. A similar thing happens when using `join`.

However, it seems like it can also make handling errors really unwieldy.

Example use case I had yesterday: I was writing some code to extract attachments passed to my share extension. There, I iterate over an array of NSExtensionItems, then for each of them, I iterate over its array of NSItemProviders, each of which should return one object. So I essentially have two levels of `when` to get a final `Promise<[Attachment]>`.

The problem is when I want to catch an error at that point. Attachment extraction may throw, for instance, `FileTooBigError`. But when I want to match that at the very end of the chain, I would have to match for `PromiseKit.Error.When(_, PromiseKit.Error.When(_, Extraction.FileTooBigError))`. Not pretty, and I couldn't care less about which of the attachments is too big.

For my own use, I wrote a helper function to get the actual error:

~~~
/// Unnests errors from .When(_, .When(_, Error))

private func flattenPromiseError(error: ErrorType) -> ErrorType {
    switch error as? PromiseKit.Error {
    case .When(_, let error)?:
        return flattenPromiseError(error)
    default:
        return error
    }
}
~~~

I use it like this in the chain, though I could also do it all the way on caller site when matching the error.

~~~
        .recover { error -> [Attachment] in
            throw flattenPromiseError(error)
        }
~~~

It seems like it could be a common problem, and could have a built-in solution. I have a few ideas:

1. Have a method/property on Promise that transforms the promise so that if it fails, it will use "raw" errors:

    ~~~
    promise.then { ... } .usingRawErrors
    ~~~

2. Have a parameter on `error`, next to `policy` to unwrap errors before passing to the closure:

    ~~~
    somePromise.error(rawErrors: true) { error in
        ...
    }
    ~~~

3. Have a parameter on `when` to configure it not to wrap errors in `.When`:

    ~~~
    when(bunchOfPromises, wrapErrors: false) // or rawErrors: true
    ~~~

What do you think?

PS. I'll be happy to provide a pull request

**Comment by swaffoja** [comment]
It would be nice for one of your solutions to be implemented. I like idea 3 myself. In my case I really don't care which of my "when" promises failed and thus don't need the index. It is important to have the index available in some cases, but my code would be cleaner if I could `wrapErrors: false`. I currently have code that looks something like this and it feels pretty clunky.

    }.error { error in

        switch error {
        case Error.When(_, let err):

            switch err {
            case URLError.BadResponse(let request, let data?, let response?):
                // handle BadResponse
            default:
                // ...
            }

        default:
            // ...
        }

    } 

I'll probably use your flattenPromiseError function in the meantime.

**Comment by mxcl** [comment]
Makes sense to me. I think the Boolean parameter is the best option.

**Comment by radex** [comment]
@mxcl would you rather have the parameter on `when` or on `error`?

**Comment by nathanhosselton** [comment]
I think it makes the most sense on `when`/`join` since it doesn't seem the parameter will have relevance outside that context. But then again, this makes the implementation potentially prone to duplication compared to if the functionality were on `error`. Perhaps this is why Max didn't specify one over the other. Regardless, it sounds like you have enough knowledge of the issue to select the solution that makes the most sense. Your PR would be happily accepted.

**Comment by radex** [comment]
Thank you — I'll think about it and will open a PR.

**Comment by mxcl** [comment]
I will implement:

```when(foo, bar, errorPolicy: .raw).catch { error in
    //…
}
```

Unless otherwise there are issues.

I reserve the option to do it like:

```when(foo, bar).unwrapError().catch { error in
    //…
}
```

Because we have a lot of `when` functions and possibly we cannot do it with the parameter.

**Comment by mxcl** [comment]
Thinking more about it, most of the time you don't care about the index, you care about the error. For PMK4 it would be nice to have a solution where the error is unchanged by default and the index can be obtained some other how.

**Comment by mxcl** [comment]
Thinking about it more, maybe this is in fact a bug? It could prevent you correctly interpreting errors.

**Comment by mxcl** [comment]
K I'm going with the idea that only the immediate caller cares about the potential index of the error, thus we will return a subclassed promise that offers a `wrapError` function that will add the index to the error.

This makes sense IMO because imagine receiving a promise from a function and `catch` on it, you don't care a `when` happened, you don't care about the index, but you may care about certain other classes of errors the `when` error may wrap and want to react to that. You don't want to have to add a pattern for when errors just in case!

Let me know your thoughts.

**Comment by mxcl** [comment]
K, this morning I came up with (for PMK4):

```swift
func when(fulfilled: a, b) -> Promise<[T]>
func when(resolved: a, b) -> Promise<[Result<T>]>  // cannot fail

// deprecate join()
```

Thinking on these issues, `join` seemed wrong to me because it forces you to write the same code in both a `then` and a `catch`, since if you are using join you clearly want to act on errors if they occur on the non-error path or you would use when.

I considered changing `join`'s behavior, since we are doing a major release, but instead felt things are clearer if we instead add mandatory parameters to when and differentiate it. This is more like Swift 3’s naming.

Thoughts?

**Comment by mxcl** [comment]
So with this, if you need the index, either use `when(resolved:)` or you can adapt your `when(fulfilled:)` to:

```swift
var index: Int!
promises = (0..<promises.count).map{ x in promises[x].recover{ err in index = x; throw err } }
when(fulfilled: promises).catch { error in
    // use error & index
}
```

Requiring the index is rare. This way consumers of promises will not need to defend against `Error.when` or `Error.join`.

**Comment by mxcl** [comment]
Closing with solution committed to PMK4 (swift-3.0 branch).

Let me know if it isn't any good, or any concerns and we'll re-open.

**Comment by radex** [comment]
Thank you. Apologies I haven't had the time to work on this — I will check out your solution in free time and leave feedback if needed :)

**Comment by radex** [comment]
Hey Max! I looked at your solution more closely and thought about it some… I think it's the right way to go! Don't see any problems with it for me.

Thanks again!
