### ISSUE TITLE
Using unowned / weak in `then` closure capture list

### ISSUE THREAD

**Issue by nivanchikov** [mxcl/PromiseKit#358]
I'm wondering whether it's valid to use **unowned self** in code like this

```
class Manager
{
    private func deleteDevice(device: Device) -> Promise<Void>
    {
        httpManager.deleteDevice(device).then({ [unowned self] (_) -> Promise<Void> in
            return self.wipeDeviceFromDatabase(device);
       });
   }

   private func wipeDeviceFromDatabase(device: Device) -> Promise<Void>
   {
        ...
   }
}
```
As per Apple Docs:
> Use a weak reference whenever it is valid for that reference to become nil at some point during its lifetime. Conversely, use an unowned reference when you know that the reference will never be nil once it has been set during initialization.

Lets imagine the instance of Manager can be deallocated at any moment and the promise chain shouldn't continue after that. So I wanted to ask whether it is valid to use `unowned self` when `self` is captured inside `then` closure or it's better to use `weak self`? The latter case introduces an issue when an optional promise can't be returned from `then`, e.g.
```
httpManager.deleteDevice(device).then({ [weak self] (_) -> Promise<Void> in
            return self?.wipeDeviceFromDatabase(device);
       });
```

> Cannot convert value of type '_ -> Promise<Void>?' to expected argument type '(Void) -> AnyPromise'

**Comment by nathanhosselton** [comment]
[Promises do not create retain cycles](http://promisekit.org/retain-cycle-considerations), so it's safe to use `self` in the handlers. Meaning that you won't even need to think about this the majority of the time. In fact, retaining `self` might even be what you want so to allow the promise to resolve before `self` is deallocated.

If you reach a situation where you do want `self` to be allowed to deallocate before your promise resolves then that's when you would employ `weak` or `unowned`. I believe the latter will catch in your `error` handler should it come up nil, but if you go this route I recommend testing. If you decide to use `weak` then you will need to refactor your promise chain to account for optional promises, which is why your second example did not compile.

**Comment by nivanchikov** [comment]
thanks @nathanhosselton, 

> If you reach a situation where you do want self to be allowed to deallocate before your promise resolves then that's when you would employ weak or unowned. I believe the latter will catch in your error handler should it come up nil

I suppose unresolved promise wouldn't reach the error handler and dealloc in case we use `unowned`, giving the following log: _"PromiseKit: Pending Promise deallocated! This is usually a bug"_. 

Anyway, thx for pointing me to the source of truth, closing the issue
