### ISSUE TITLE
Deprecated method use in NSURLConnection+Promise

### ISSUE THREAD

**Issue by rlaferla** [mxcl/PromiseKit#369]
```
            NSURLConnection.sendAsynchronousRequest(request, queue: Q, completionHandler: { completionHandler($1, $0, $2) })

'sendAsynchronousRequest(_:queue:completionHandler:)' was deprecated in iOS 9.0: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h

```

**Comment by nathanhosselton** [comment]
Unfortunately there are a number of methods/classes used among the PromiseKit categories that were deprecated in iOS 9 that we will have to continue to support for the time being (UIAlertView etc). I've looked into updating this specific method but it does not trivially map to its replacement. I'll leave this open anyway because unlike the other deprecations it should be possible to update this one without breaking the API. PR welcome.

**Comment by mxcl** [comment]
I've removed deprecated stuff from PMK4 since it has been two years since the deprecation now. They are going to be still available in a subspec. Nothing else we've been able to do, removing them outright earlier would have been outrageous to people who needed them. CocoaPods doesn't let us turn on no warnings, and you can't turn off warnings in the source code in Swift (just objc).

**Comment by NinjaSudo** [comment]
@mxcl you mentioned a subspec for the NSURLConnection category that can be used in PMK4, where does this live? I plan to migrate over to different methods, but after a migration to Swift 3, etc needed to upgrade.

**Comment by mxcl** [comment]
https://github.com/PromiseKit/Foundation

FFR you can read the `.podspec` file for any CocoaPod to have a direct pointer to where things live.

**Comment by mxcl** [comment]
It's a single file though, so you can just drop it into you project and it'll just work.
