### ISSUE TITLE
calling multiple promises simultaneously?

### ISSUE THREAD

**Issue by foobar8675** [mxcl/PromiseKit#385]
Does promise kit have the concept of (in js, bluebird) .all or .map where you can call n number of promises simultaneously?

in js, i might do something like this

````
		var promises = [];
		promises.push(model.DailyTotal.destroy(where));
		promises.push(model.Membership.destroy(where));

		Promise.map(promises, function(promise) {
		return promise;
			},{concurrency:2})
			.then(function() {
				done();
			})
			.catch(function(err) {
				console.log(err);
				done(err);
			});
	},
````

**Comment by lifely** [comment]
Hey @foobar8675,

I was looking for something similar, i since i think i might have my answer, i'll take some time and share it for you.

I think we can both achieve what we want through a simple `PMKWhen` : 
 > http://promisekit.org/when. 

However if you read the documentation right you'll might also be interested in a `join:` promise: 
 > http://cocoadocs.org/docsets/PromiseKit/1.4.2/Classes/PMKPromise.html#//api/name/join:  

Note there's also some drawback to using a join closure. One of the other drawback i find is that there not easy way to apply a timeout to such grouped promise.

The documentation does reference the availability of `NSProgress` on promise, but i wish a timeout behaviour would be available out of the box.

Anyway, thanks for the work peeps.

**Comment by foobar8675** [comment]
@lifely that's exactly what i was looking for!
