### ISSUE TITLE
swift-2.0-minimal-changes branch breaks with Swift 2.2

### ISSUE THREAD

**Issue by pwerry** [mxcl/PromiseKit#390]
Compiler complains of redundant `CustomDebugStringConvertable` declaration on `AnyPromise` extension in `AnyPromise.swift`

**Comment by nathanhosselton** [comment]
Thanks for the notice. Though, the minimal changes branch was never meant to be a continually supported version of PK, I'm sorry to say. It was mostly provided as a convenience to prevent forcing users to adopt all changes of PK3 right away. If it is now broken, it's unfortunate, but it's unlikely that one of us will get to it unless there is an outpouring of requests or some greater need emerges. And in fact, any updates would likely need to go on a branch off this one, as updating to support Swift 2.2 would break compatibility for anyone relying on this branch for Swift 2.0 support. Of course if someone were to provide a PR, we could merge it into a new `swift-2.2-minimal-changes` branch, but officially it's not something that is in scope.

Again, apologies. But due to already-strained developer-hours available from primary contributors, our focus will likely remain on the critical branches for the foreseeable future. I'll update the documentation to indicate that the branch is Swift 2.0/2.1 only.

**Comment by brianhv** [comment]
Someone created a fork here with the (very small) change required to fix this error.
Fork: https://github.com/SLab7/PromiseKit/tree/swift-2.0-minimal-changes
Commit: https://github.com/SLab7/PromiseKit/commit/1ffca8f0bb5dbce68d7f921a208527896b98a1fd

**Comment by nathanhosselton** [comment]
@brianhv thanks for pointing us to this. I've messaged him to ask if he would like to open a PR. If not, I guess I'll just apply this myself after all as it is quite tiny, assuming nothing else needs to be done.
