### ISSUE TITLE
Why adopt wrapper API for NSURLSession category, instead of native Apple API's?

### ISSUE THREAD

**Issue by sstadelman** [mxcl/PromiseKit#403]
I'm very concerned about this apparent strategy of implementing NSURLSession extension methods as the `GET`, `POST`, etc. interface, instead of the true `dataTaskWithURL()` style of interface.  What is the logic behind this move? --it really impacts the developer heavily.  

> As a developer, I want to adopt PromiseKit, and integrate it into my application in a compatible way with my current networking stack, with minimal disruption.  I should not need to adopt a new networking interface, in order to utilize PromiseKit.

If PromiseKit is going to provide standard wrapper implementations of the native Apple API's, (which is great), I'd think they ought to stick closely to those native API's.  I would reference this project: https://github.com/jschmid/NSURLSession-PromiseKit/blob/master/Pod/Classes/NSURLSession%2BPromiseKit.m as a model.  It seems perfectly logical to provide PromiseKit-wrapped implementations of the OMG API's *also*, but not to provide the OMG interface as a wrapper for the NSURL.

Is there a particular reason for this decision, or would it be possible to provide the NSURL-style interface also?

**Comment by nathanhosselton** [comment]
I do not have knowledge of Max's intentions with this part of the API, and I do not speak for him. But from my perspective they seem to be provided out of convenience, since the NSURLSession API is somewhat clunky I think, and for me at least they fulfill on that goal. But I can understand that working with them, especially if refactoring existing code that uses NSURLSession's default API, may not always be convenient. Is this your concern, and is the provided `pomise(request:)` on NSURLSession then not sufficient?

I am open to the idea of providing more familiar methods with the extension. Is @jschmid's implementation in line with what you're seeking?

**Comment by mxcl** [comment]
The categories are convenience functions, nothing is stopping you from writing your own promise wrappers for NSURLSession. Please do so!

**Comment by sstadelman** [comment]
@nathanhosselton @mxcl Thanks, that's fair.
