### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by dkliman** [mxcl/PromiseKit#419]
hi,

`D=$(osascript -e 'tell application "Xcode" to get path of project 1'); cd "$D/..”`

that command won't work with the directory names that i have, which contain spaces.

`D=/Users/dkliman/Documents/iOS dev experimentation/Labels test/Labels test.xcodeproj; cd /Users/dkliman/Documents/iOS: No such file or directory`

also I'm still quite a beginner at iOS and swift, so i could be doing something wrong, but i was able to manually move into the correct directory and run the script...

but I don't think it worked...

Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    xcodeproj 'path/to/Project.xcodeproj'

```
Daves-MacBook-Pro:Labels test.xcodeproj dkliman$ osascript -e 'tell application "Xcode" to quit' && open *.xcworkspace
LSOpenURLsWithRole() failed with error -600 for the file /Users/dkliman/Documents/iOS dev experimentation/Labels test/Labels test.xcodeproj/project.xcworkspace.

```

**Comment by nathanhosselton** [comment]
All the first script does is `cd` to the directory of the Xcode project that is currently open. It's just a shortcut. You can `cd` manually otherwise. I will fix it though since it does need to be able to account for spaces in directory names.

And the second script simply closes the Xcode project file and opens the new Xcode workspace file that is created after running `pod install`. So you can also do that manually.

Not sure why cocoapods is forcing you to specify an Xcode project file. Did you put your Podfile in the same directory as the Xcode project file? You can also just do what the error says i.e. in the Podfile specify the path to the project file relative to the location of your Podfile.

**Comment by nathanhosselton** [comment]
Also, welcome to iOS! We're stoked your starting off with PromiseKit.
