### ISSUE TITLE
Error handling swift throw not catching

### ISSUE THREAD

**Issue by udaypatial** [mxcl/PromiseKit#442]
I have a method as below:
The issue is that when I throw something from recover. It does not throw it back to the actual calling function get(), as it does for line //1. throw DPError.Error
Because of this I am not able to catch any error.
Is there a way to make this happen or am I missing something here. Can't find anything related to this in the documentation.

```swift
func get(req: NetRequest, fn: NSData? -> ResponseModel?) throws -> Promise<(NetResponse, ResponseModel)> {
	//1. throw DPError.Error
	return NSURLSession
		.GET(req.url)
		.asDataAndResponse()
		.then { (data, resp) -> Promise<(NetResponse, ResponseModel)> in
			let httpStatusCode = (resp as! NSHTTPURLResponse).statusCode
			let model = fn(data) //parse conditionally of course
			return Promise(NetResponse(statusCode: httpStatusCode, errorCode: nil, respBody: data), model!)
		}.recover { body -> Promise<(NetResponse, ResponseModel)> in
			let error = body as NSError
			throw DPError.Error
        }
}

enum DPError: ErrorType {
	case Error
	case STCIPRangesError(apiType: String, errorType: String, errorCode: Int)
	case STCMSISDNError(apiType: String, errorType: String, errorCode: Int)
}
```

**Comment by mxcl** [comment]
The issue is that when I throw something from recover. It does not throw it back to the actual calling function get(), as it does for line //1. throw DPError.Error
Because of this I am not able to catch any error.

Well, yes. This is expected. When you do this:

```
func get(req: NetRequest, fn: NSData? -> ResponseModel?) throws -> Promise<(NetResponse, ResponseModel)> {
    throw DPError.Error
}
```

You are throwing synchronously.

When you do this:

```
func get(req: NetRequest, fn: NSData? -> ResponseModel?) throws -> Promise<(NetResponse, ResponseModel)> {
    return Promise {
        throw DPError.Error
    }
}
```

You are throwing asynchronously. The error is thrown **inside** the promise chain, which happens **later**.

You need to add a `error` handler for the promise chain in order to catch the error.
