### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by kwstasna** [mxcl/PromiseKit#469]
Hello guys. Thanks for your great library here!!

Wanted to ask you a newbie question. I'm now starting learning swift and of course i'm a bit confused with asynchronous functions. I'm using Parse to get and to save data.
So i have 2 functions.

```
func one() {
brings all the likes of the user and save them into an array
}

func two() {
brings all the posts and append them to a cell
}
```

I would like you to give me an example of your promises how to make `func two()` to run ALWAYS when `func one()` finishes.

I was thingking about calling `func two()` within the success closure of the `func one()` but its not that good coding quality.

Thanks a lot for your time and sorry if this is a newbish question at all. Trying to learn quality stuff!

**Comment by mxcl** [comment]
```swift
two().always {
    return one()
}
```

Presuming `one()` and `two()` return `Promise`.

**Comment by kwstasna** [comment]
Is there any example in your files?

**Comment by nathanhosselton** [comment]
Probably http://promisekit.org/sealing-your-own-promises/ is a good place to start. It even has examples that use Parse.

Also, building off the prior example, if you only want `two()` to run when `one()` is _successful_ (which is the common pattern), you would use `then` instead of `always` and act on failure of either within `error`:
```swift
one().then { (likes) -> Promise<[Post]> in
    // handle likes
    return two()
}.then { (posts) in
    // handle posts
}.error { (error:ErrorType) in
    // Display a message to the user, etc
}
```
Again, presuming that `one()` and `two()` both return Promises.

Note that `error` ends the promise chain. If you wish to handle an error and continue the promise chain you would use `recover` before `error`.
