### ISSUE TITLE
"Pending Promise deallocated!" error but only on iOS 8

### ISSUE THREAD

**Issue by sryze** [mxcl/PromiseKit#472]
I'm getting this error when running an app on iOS 8.x simulators 100% of the time, however on iOS 9 everything is working perfectly (both on the simulator and a real device).

As a result, the promise seems to be is never fulfilled. I think might be related to the use of PMKWhen() as it happens in one of the few places where I use it.

Also, in the debugger, I see an entry like `Enqueued from com.apple.main-thread` where one of the stack frames is a call to `resolve` inside a block passed to `+[AnyPromise promiseWithResolverBlock:]`. But I'm not sure what to make of it.

What's the best way to debug this error?

**Comment by mxcl** [comment]
Please provide code example

**Comment by sryze** [comment]
Well, this is kind of complicated. There are a lot of promises involved in the chain, I highly doubt I will be able to give a minimal example code to demonstrate this.

However, I think it might be related to my NSProxy subclass and the way it retains (or doesn't retain) promises. Here's what its main business looks like:

```
- (void)forwardInvocation:(NSInvocation *)invocation {
    [invocation retainArguments];
    
    __unsafe_unretained AnyPromise *promise;
    [invocation invoke];
    [invocation getReturnValue:&promise];

    AnyPromise *newPromise = promise.catch(^id (NSError *error) {
        // ... Return another promise or error here...
    }).then(^id (id result) {
        NSManagedObjectContext *context = [NSManagedObjectContext MR_defaultContext];
        if (!context.hasChanges) {
            return result;
        }
        return [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve) {
            [context MR_saveToPersistentStoreWithCompletion:^(BOOL contextDidSave, NSError *error) {
                if (error != nil) {
                    resolve(error);
                } else {
                    resolve(result);
                }
            }];
        }];
    });

    [invocation setReturnValue:&newPromise];
}
```

The purpose of this proxy is to forward the method call to one of two objects that implement the same protocol based on a certain condition. Do you see anything obviously wrong / possibly problematic here?

**Comment by sryze** [comment]
Forgot to mention: I spotted this error in a totally different place on iOS 9 too (which happens to use `PMKWhen` as well), it may be not OS version specific after all. 

I'll try downgrading to PromiseKit 1 and see what happens. I'll let you know what I find.

**Comment by mxcl** [comment]
Well, this is naively suspicious:

```
__unsafe_unretained AnyPromise *promise;
```

The handlers do *not* hold onto their promise (only the new promise they return), so if nothing else is holding onto the promise it will deallocate.

However since you say `appears in call stack` in a then off of that promise, it must be resolved, so… I'm confused.

There are 4 promises here:

1. The promise from the `NSInvocation`
2. The promise returned by `catch`
3. The promise returned by the `then` off the `catch`
4. The promise returned in the `then`

2 is retained by the block you pass to `catch` (strictly a block in PMK retains your handler and the promise), 3 is returned by the block you pass to `then`, so unless I'm confused about how the retains are going on I can't immediately see where the deallocation is happening *before* a promise can be resolved.

When a value is returned by a handler the promise is resolved synchronously so it should not be able to deallocate in between the value being returned and the promise being resolved by that value.

**Comment by sryze** [comment]
Thanks for the reply. I replaced PromiseKit 3 with 1.7 a couple of days ago and it's been working great so far. I think I'll close this for now.
