### ISSUE TITLE
Is it fine to not assign a promise to a variable?

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#511]
I'm trying to get my head around two things:
- Xcode is giving me a warning if I don't assign the result of a function that returns a promise. This warning seems not promise specific but if you haven't disabled it it might be for good reasons
- My promise are getting deallocated (`Pending Promise deallocated! This is usually a bug`) and stop executing and I don't get why

For instance, is it fine to do

```swift
func getNewToken() -> Promise<Void> {
  return Promise { fulfill, reject in
    guard let token = refreshToken else {
      reject(TokenError.tokenExpired)
      return
    }
    Network.shared.apiRequest( // this returns a promise, but I'm not allocating it's result
      "auth/refreshtoken",
      method: .post,
      data: [ "refreshToken": token.value ])
      .then { payload -> Void in
        try self.setToken(fromPayload: payload)
        fulfill()
    }
  }
}

// somewhere else
getNewToken() // I'm not allocating the promise result either
.then {
  print("token has been refreshed")
}
```
?

**Comment by mxcl** [comment]
* The compiler warning is because an unterminated Promise chain is a chain that doesn't end in `catch`, and thus has no error handling.
* The log warning is what it says, you have an unresolved promise somewhere and you don't want that. It may well be the code sample since the error path is not handled (there is no reject).

Your code could be made more robust anyway:

```swift
func getNewToken() -> Promise<Void> {
  guard let token = refreshToken else { return Promise(error: TokenError.tokenExpired) }

  // by always returning promises you ensure that error paths
  // and fulfillment paths are ALWAYS handled

  return firstly {
    return Network.shared.apiRequest("auth/refreshtoken", method: .post, data: [ "refreshToken": token.value ])
  }.then { payload -> Void in
    try self.setToken(fromPayload: payload)
  }
}
```

By using promises you are ensuring you always handle errors and always handle positive paths too.

**Comment by gsabran** [comment]
Ah excellent good point. I should have taken the warning much more seriously. Thanks a lot for the help!
