### ISSUE TITLE
Carthage fails to build swift-2.3-minimal-changes

### ISSUE THREAD

**Issue by FranciscoAmado** [mxcl/PromiseKit#546]
Hi guys,

I've been trying to support 2.3 on my app and on updating PromiseKit it fails to update through `Carthage`
By checking the xcodebuild output it appears to have something to do with PromiseKit being imported on AVFoundation but I can't figure out a way to bypass this.

```
/MyProject/Carthage/Checkouts/PromiseKit/Extensions/AVFoundation/Sources/AVAudioSession+Promise.swift:4:8: error: no such module 'PromiseKit'
import PromiseKit
       ^
```

Is it a known issue?
I'm willing to help if needed.
Thanks for building PromiseKit,
Francisco

**Comment by mxcl** [comment]
Please provide your `Cartfile`.

**Comment by FranciscoAmado** [comment]
Oh sure,

I've just tried with `github "mxcl/PromiseKit" "swift-2.3-minimal-changes"`

**Comment by mxcl** [comment]
Well something is amiss then because the `swift-2.3-minimal-changes` branch has no `Extensions` directory:

https://github.com/mxcl/PromiseKit/tree/swift-2.3-minimal-changes

Also FYI, as our README says, you should use `3.x` for Swift 2.3:

    github "mxcl/PromiseKit" ~> 3.5

The minimal changes branch is for migrating PromiseKit 2 which is over two years old now.

**Comment by FranciscoAmado** [comment]
That should be it.

I've tried before with 3.5 and was having the same issue. Cleaned up everything, rebuilt it and worked now.

Sorry for the trouble and thank you for the help
