### ISSUE TITLE
Consider providing overloads for tuple returns of promises

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#560]

**Comment by FilipZawada** [comment]
Can you post an example of desired functionality please?

**Comment by mxcl** [comment]
```swift
asyncThing().then {
    let foo = promise1()
    let bar = promise2()
    return (foo, bar)
}.then { promise1Result, promise2Result in
    //…
}
```

**Comment by FilipZawada** [comment]
Cool, we'll have to add type declaration I guess:

```
Promise(value: 0).then { _ -> (Promise<String>, Promise<String>) in
    let foo = Promise(value: "foo")
    let bar = Promise(value: "bar")
    return (foo, bar)
}.then { foo, bar -> Void in
    print(foo + bar) // foobar
}
```

I'll try to have PR ready by tomorrow.

**Comment by mxcl** [comment]
Great, I think it'll make a good addition, provided it doesn't cause the Swift compiler to get confused by other usages. Which is my main concern. Swift already gets confused by PromiseKit enough.

**Comment by FilipZawada** [comment]
As a starting base I made a very minimalistic [implementation](https://github.com/FilipZawada/PromiseKit/commit/3740e99f2aadb2062e2bdb97e92541dc335898c5).

And now I wonder about few things:
* I made a support only for 2 & 3-values tuples. I feel at least 5 values should be allowed, however as for now I wanted to be consistent with `when`.
* I can't think about any way of allowing infinite number of promises in a tuple (except hacking with dangerous unsafeBitCast).
* I haven't added tuples functionality to `firstly`, since `firstly` already doesn't match `then` functionality. I guess you kept it intentionally thin?
* I haven't touched objc at all. Should I provide an adequate implementation too?
* I've provided a very minimalistic set of tests. E.g. do you find a rejection test useful? (I can add it)

What are your thoughts?

**Comment by FilipZawada** [comment]
P.S. I will add a missing test case when one of returned promise is a `self`

**Comment by mxcl** [comment]
> I made a support only for 2 & 3-values tuples. I feel at least 5 values should be allowed, however as for now I wanted to be consistent with when.

By all means add support for more, and feel free to increase the size of when also.

> I can't think about any way of allowing infinite number of promises in a tuple (except hacking with dangerous unsafeBitCast).

I would be interested in seeing the code, but yeah, sounds binary unsafe.

> I haven't added tuples functionality to firstly, since firstly already doesn't match then functionality. I guess you kept it intentionally thin?

`firstly` is an odd one, we for example don't have an `on` parameter because firstly always executes immediately, and thus we don't unleash zalgo. I think we should support the tuple return for firstly, I think the only reason we didn't initially is Swift compiler issues.

> I haven't touched objc at all. Not even sure if there's anything to do on that side.

Yeah, feel free to leave it alone, the equivalent is `PMKManifold` and we chose not to make that behave like `when` some time ago.

> I've provided a very minimalistic set of tests. E.g. do you find a rejection test useful? (I can add it)

Probably rejection is covered, but more tests is good.

**Comment by FilipZawada** [comment]
PR: https://github.com/mxcl/PromiseKit/pull/593

**Comment by FilipZawada** [comment]
@mxcl Any chances to look at that?

**Comment by mxcl** [comment]
Sorry for the delay. I wanted to try it out more.
