### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by NikKovIos** [mxcl/PromiseKit#624]
What about providing an example application? Documentation is good, but there are some points which are difficult to understand.

**Comment by mxcl** [comment]
I wrote this a while back, but since have developed new techniques.

https://github.com/mxcl/Kissogram

I would love to offer something more complete, but all my work is for private corps, and they won't open source. In-between that time I maintain the library, I can't really dedicate the time to making a complete sample app.

**Comment by mxcl** [comment]
Closing because issues are not a good place for wishlists. PR welcome though. Discussion will cause me to reopen the ticket.
