### ISSUE TITLE
when(resolved:) with promises that return different types

### ISSUE THREAD

**Issue by victoraraujo01** [mxcl/PromiseKit#657]
* PromiseKit version: 4.1.7
* Xcode version: 8.3.1

Hi, I have to join two separate chains of promises into one that depend on both. One of the two original promises, however, can fail and the code should continue its execution. Let me clarify with a little bit of code:

```
promiseThatMayFail:Promise<X> = ...
promiseThatMustSuceed:Promise<[Y]> = ...

finalPromise = when(resolved:[promiseThatMayFail, promiseThatMustSuceed]).then {...}
```

This code, however, doesn't compile because Xcode complains that all promises passed in the array to the ```when(resolved:)``` method are not of the same type. Using the syntax provided in the documentation (http://promisekit.org/docs/handbook/Functions.html#/s:F10PromiseKit4whenurFt8resolvedGSaGCS_7Promisex___GS0_GSaGOS_6Resultx___) also does not work.

Is ```when(resolved:)``` really supposed to work only with promises of the same type or am I doing something wrong?

PS: Everything works fine if I use ```when(fulfilled:)```

**Comment by mxcl** [comment]
`when(resolved:)` takes an array, with Swift `Array` has to have a known type, thus the type has to be the same. `when(fulfilled:)` has a few convenience varieties that take a tuple instead, tuples can be specified with varying types.

So yes, as it stands, `when(resolved:)` requires the promises to be the same type as can be seen from the declaration.

As per the FAQ on this topic, the easiest way to get around this is to make all the promises `Void` by using `asVoid()` and then to unwrap the original promise’s value in your `then`:

```swift
when(resolved: [a.asVoid(), b.asVoid()]).then { results in
    if let resultA = a.value {
        //…
    }
}
```

Or don’t use `when(resolved:)`; honestly, most of the time when people want to use it it is because they are using promises wrong. I have used `when(resolved:)` twice in 5 years of constantly using PromiseKit.

**Comment by mxcl** [comment]
> Or don’t use when(resolved:); honestly, most of the time when people want to use it it is because they are using promises wrong. I have used when(resolved:) twice in 5 years of constantly using PromiseKit.

Like for example, you said you must recover from one of the two promises, but not the other, so maybe you should use `recover`:

```swift
let b = a.recover { err -> Void in 
   // error handling
}

when(fulfilled: a, b).then {
    //…
}.catch {
   // this won't happen if a fails
}
```

**Comment by victoraraujo01** [comment]
```recover```was exactly what I needed! Don't know why I overlooked it when I read the documentation. Thank you very much for the answer!
