### ISSUE TITLE
How can I use the previous result?

### ISSUE THREAD

**Issue by hengchengfei** [mxcl/PromiseKit#678]
how can I use the previous 'username'?

```swift
 when(fulfilled: self.getUserName()).then{ username in
               self.update(username)
            }.then { isSuccess in
                // username can't be used at this place?
               self.search(username)
            }
```

**Comment by nathanhosselton** [comment]
There are a few options. You can:

- Make `self.update` fulfill with `username` instead of with the boolean `isSuccess` value (which is unnecessary since if the process was unsuccessful the promise should be rejected and you should handle that in a `catch`).

- Assign `username` to a higher scope (which `self.update` may already be doing?)

- Access the `value` of the promise underlying `getUserName()`, which in your case could be accomplished my making the function into a property since it takes no parameters (unless you need to make the request multiple times).

Let me know if you'd like examples of any of these. Also, your use of `when` is superfluous as it is only taking a single promise, so you can drop it.

**Comment by mxcl** [comment]
```swift
getUserName().then{ username in
    self.update(username).then{ ($0, username) }
}.then { isSuccess, username in
    self.search(username)
}
```

**Comment by mxcl** [comment]
Assuming resolved.
