### ISSUE TITLE
Carthage PromiseKit 1.7.3 - NSURLConnection+PromiseKit in Swift

### ISSUE THREAD

**Issue by skela** [mxcl/PromiseKit#718]
* PromiseKit version: **1.7.3**
* Xcode version: **9**
* Carthage version: **0.25.0**

So I'm still using version 1.7.3 of PromiseKit in an app, and I'm trying to reduce the time it takes to build my app by moving from Cocoapods to Carthage. I've been using PromiseKit as a pod without any issue. Just want to swap that with a framework built using carthage instead.

Everything seems to be working apart from 1 issue. In my Swift code (project is mixed objc / swift btw), its giving me an error about "Type 'NSURLConnection' has no member 'promise'".

My Cartfile has the following
`github "mxcl/PromiseKit" ~> 1.7`
`github "mxcl/OMGHTTPURLRQ" ~> 3.2`

I've tried with and without OMGHTTPURLRQ in it.

I'm not sure what else to try, presumably I'm missing something in my Bridging header, but I can't figure out what that would be.

**Comment by mxcl** [comment]
Our Carthage has never provided the Foundation, UIKIt, etc extensions because Carthage is not flexible like CocoaPods so we cannot provide “submodules” so users could not choose whether or not to have the extensions like they can with our Pod.

Thus you have to add them yourself. Grab the sources for each extension you want at https://github.com/PromiseKit either manually or with submodules.

If you were to use a newer version of PromiseKit you can add these dependencies additionally in your `Cartfile`, however we did not add this feature until PMK3, so you cannot do without causing Carthage to pull at least PMK3.

There are more details in our installation instructions, but we don't really go into the details for PMK1 since we honestly didn't think anyone was still using it! Sorry.

**Comment by skela** [comment]
Yeah I don’t want to keep using version 1 , but I’m stuck as I can’t upgrade to higher versions due to the time that would take to do so :( i looked at having both versions side by side and upgrading as I go along, but I was never able to do so. So I better keep using version 1. It works amazingly well still, not had a single issue with it.

:(

**Comment by skela** [comment]
Anyway thx , I’ll give the submodule approach a try.

**Comment by mxcl** [comment]
Actually, IIRC the extension sources are provided with PMK1, so you can just add them from the Carthage checkout.

Still manual though.

**Comment by skela** [comment]
Yeah I had the exact same idea, but I'm getting some exceptions when doing that, so trying to figure out why thats happening (i.e. no build time errors, but some run time exceptions):

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSURLConnection promise:]: unrecognized selector sent to class 0x10cc00348'

**Comment by skela** [comment]
Never mind, had added the files to the xcode project but xcode didnt mark them to belong to the target. Once i updated the target memberships for these files, it started working.

Thanks as always @mxcl ! 

PS: If you have any guides  or have any tips on how to bring both new and old promisekit into the same project, let me know. 👍
