### ISSUE TITLE
Have us run the Promises/A+ via a JavaScript bridge

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#789]
We have re-implemented the suite as Swift, but this means:

1. We don't test Guarantee & AnyPromise (though since all the code is now in `Thenable` this probably is not a big deal).
2. Any updates to the suite do not come our way.

A JS bridge shouldn’t be a large undertaking and would give us the additional reassurance that we didn't make any mistakes.

**Comment by ldiqual** [comment]
Fyi since I had experience with JSC from a past job, I've started working on this here: https://github.com/ldiqual/PromiseKit/tree/lois-jsaplus/Tests/JS-A%2B

Some (most?) of the tests pass but I still have a large amount of debugging to do. Working with JSC is pretty tedious since stacktraces don't have line numbers.

**Comment by mxcl** [comment]
Wow! Amazing work.
