### ISSUE TITLE
Renamed or otherwise version 1 to enable having both version 1 and version 6 of the library in a project

### ISSUE THREAD

**Issue by skela** [mxcl/PromiseKit#791]
Its getting increasingly obvious that I need to upgrade to version 5/6.
Sadly I'm still on version 1, and its a pretty big task to upgrade to 5/6.
So I wanted to raise an issue here asking if anyone knows about or has a fork or something limilar with renamed classes / files, to enable having both version 1 and version 5/6 of PromiseKit in the same project.

**Comment by mxcl** [comment]
Well, if you install them yourself (without CocoaPods), then they should be able to coexist since they have different class names. There may be a little overlap, but probably easy to fix.

6 is definitely the best PromiseKit, but unless you are also using Swift, then the objc side is pretty much the same as 1.x.

Certainly there is nothing I know of that can help with the migration, but if you can get them installed side by side then you can do it gradually.

**Comment by skela** [comment]
I like the look of 6, so def going to go with that if I can. And yes my plan is to have them side by side then gradually faze out all the version 1 stuff. 

So was planning on integrating promise kit 1 via a git submodule , then integrate promisekit 6 via carthage. That not a good way to do it?

When you say install it yourself, do you mean adding the Sources stuff directly to my project, or adding the projects to the workspace and integrating it that way?

**Comment by mxcl** [comment]
Yes install yourself is like via a submodule.

**Comment by mxcl** [comment]
Closing, but discussion here can continue.

**Comment by skela** [comment]
Thx max
