### ISSUE TITLE
How to use when() on an array of Guarantee<T>

### ISSUE THREAD

**Issue by tealshift** [mxcl/PromiseKit#861]
--- PromiseKit 6
I found this:
```when(guarantees: [Guarantee<Void>])```

But it clearly does not support Guarantees with return values. Why?
I'm trying to wait on a list of `Guarantee<Int>`.

**Comment by tealshift** [comment]
Okay, I may have actually misunderstood something. Is there not a way to acquire the array of `Result` "values" of the results from the array of Promises/Guarantees?

I read this section https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#waiting-on-multiple-promises-whatever-their-result
but it confuses me.
It says " `Result` is an enum of `.fulfilled` or `.rejected`" but what about accessing the values that the results that were fulfilled with?

**Comment by mxcl** [comment]
When I initially tried to provide all the logical types of `when` Swift found the situation ambiguous making it impossible to provide all without making all painful.

So for now, until Swift is better, you can do what our documentation recommends and `asVoid()` all the guarantees and then extract out their value afterwards because you kept a reference to each one from before.

**Comment by tealshift** [comment]
Oh, I see. Thanks for the suggestion. :)
