### ISSUE TITLE
Siwft 4.2 conversion warning in xcode 10

### ISSUE THREAD

**Issue by volkanbicer** [mxcl/PromiseKit#938]
Version 6.4.1

There is swift version if/else statement in UIView+Promise file. That causes swift 4.2 conversion warning on xcode 10. 

Please remove the old code code or create a new branch or release for that.

**Comment by mxcl** [comment]
Per our installation documentation this is a CocoaPods issue that you have to add code to your Podfile to work around:

https://github.com/mxcl/PromiseKit/blob/master/Documentation/Installation.md

If this is a problem you can switch to Carthage or comment on the issue ticket they have that is open for them to fix this problem.

> There is swift version if/else statement in UIView+Promise file. That causes swift 4.2 conversion warning on xcode 10.

This is not the problem the problem is CocoaPods does not set the correct Swift version on the target it generates for PromiseKit. PromiseKit supports Swift 3 through 4.2 and thus this if/else statement is required or we would not actually support this full range of Swift versions.

This issue has now been opened three times, please consider searching for existing closed issues before opening new ones in future.

**Comment by volkanbicer** [comment]
Thanks it's worked.
