### ISSUE TITLE
Documentation request - Box class comments

### ISSUE THREAD

**Issue by brynjar** [mxcl/PromiseKit#969]
Hi,

I'm trying to understand the promisekit source - the Box class is particularly essential yet it contains various FIXME/TODO comments that make it sound half finished. They also don't fully explain what they set out to do, IMHO.

Also, the use of the barrier syncs is not entirely clear (I presume 99% of the time these have no effect at run time, but handle that 1% of the time race condition or other)

This class has two variants on the inspect method that are called from the Promise class pipe method, in succession, again not documented why.

Finally, objects of EmptyBox type only start out 'empty' so wondering as to the naming here.

**Comment by mxcl** [comment]
Yes, Box is internal, so I didn't document it. Apologies. The `Box` class represents the wrapped `Result` of a promise and exists to ensure access to it is thread safe.

> the Box class is particularly essential yet it contains various FIXME/TODO comments that make it sound half finished.

There is one FIXME and one TODO which both represent the same single potential issue. However I have since concluded this situation is fine since the issue relates to the order of handlers being correct, yet this situation can only occur for a handler added independently of any others, so the order would be unimportant to the caller.

> Also, the use of the barrier syncs is not entirely clear (I presume 99% of the time these have no effect at run time, but handle that 1% of the time race condition or other)

Yes, they are there for thread-safety.

> This class has two variants on the inspect method that are called from the Promise class pipe method, in succession, again not documented why.

One of them returns the wrapped `Result`, the other provides a closure that is wrapped in a barrier sync to allow thread-safe modification of the box.

> Finally, objects of EmptyBox type only start out 'empty' so wondering as to the naming here.

The name is opposed to the `SealedBox` type, the `SealedBox` starts sealed, which is used as an optimization when a Promise is initialized with a value, thus we avoid needing barrier syncs. The EmptyBox starts empty, but is eventually “filled” when the promise it represents is resolved.

**Comment by brynjar** [comment]
ok, thanks for the info.
