### ISSUE TITLE
are there "doubling up" drawbacks other than poor style?

### ISSUE THREAD

**Issue by bradwbradw** [mxcl/PromiseKit#989]
[The Appendix section on doubling up](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md#doubling-up-promises) describes the anti-pattern of using promises nested inside other promises, instead of creating a nice promise chain.  Unfortunately, in a project i'm working on, I've needed to move quickly and ended up implementing a bunch of calls in the nested way ("doubling up"), just to get around compiler errors (i'm still new with this library).  I'm considering cleaning it up, but i'm not sure what gain there is other than things like good style, future maintainability, less code (less bugs), readability...  All these are important of course, but i'm just wondering if there are any more severe drawbacks, perhaps to do with performance or security (or anything else)

**Comment by mxcl** [comment]
* It means cancelation will cause your promises to never resolve
* It makes it trivial to create chains that don’t resolve by mistake since you could easily overlook a place you need to “double-up”
* It makes it harder to read the chains, thus violating one of the main reasons to use promises in the first place

So the first one is a definite problem unless you make all your catches `catch(policy: .allErrors)`, but cancelation is rare. See the cancelation documentation for more information.

I sincerely recommend correcting the doubling up, it hides bugs.

**Comment by bradwbradw** [comment]
Thanks for the info / advice.  i'll do some research and follow up if i have any more Q's.

**Comment by mxcl** [comment]
Undoubling is usually easy, eg:

```swift
return Promise { seal in
    foo().then {
        bar()
    }.then {
        seal.fulfill($0)
    }.catch {
        seal.reject($0)
    }
}
```

Becomes:

```swift
return foo().then {
    bar()
}
```

Which I think shows how much clarity you gain too.
